### PR TITLE
Support castling

### PR DESCRIPTION
**Pull request by justinrjoseph**
- Added has_moved? attribute to pieces
- Added castle_move?(x, y) method to King model with castling logic
- Switch is_obstructed? and valid_move? calls in move_to! method on Piece model
- Added Rook instances to King test and tests for auto-move logic for rooks
- Added integration tests for castling logic
- Removed unnecessary directory in code base

### CODE REVIEW

**Comment by xJIsaac** [comment]
How do you perform this move in the game?

**Comment by justinrjoseph** [comment]
Assuming your king hasn't moved, and at least one of your rooks also hasn't moved...you move your king two spaces toward the rook you desire to castle with. The current logic updates the king to Y3 or Y7, and the rook is updated to Y4 or Y6.

I'll update this PR to resolve the conflict ASAP.

**Comment by xJIsaac** [comment]
Ok cool. It works now.

**Comment by xJIsaac** [comment]
It's awesome you got it to work! :+1: 
However, not all requirements of castling appear to be checked. Namely, requirements 3-6 below.
1. The king and the chosen rook are on the player's first rank.[3]
2. Neither the king nor the chosen rook has previously moved.
3. There are no pieces between the king and the chosen rook.
4. The king is not currently in check.
5. The king does not pass through a square that is attacked by an enemy piece.[4]
6. The king does not end up in check. (True of any legal move.)

Here castling occurred while the opponent's knight was in position to attack F1 breaking the 5th requirement. This also failed in instances where the black knight was in position to check the king in it's original position (before castling) and it's final position, which breaks 4 and 6. Perhaps, we could use a new method to detect threats on a given square and check for them.
screen shot 2016-03-30 at 4 42 39 pm

Here castling occurred while my queen occupies B1 breaking the 3rd requirement. Perhaps we should incorporate 'is_obstructed?' here.
screen shot 2016-03-30 at 4 52 47 pm

Then here was just a bug I found. I wanted to test for moves made in error. Castling shouldn't occur here since my queen is at C1. When I moved my king to C1 over the queen, my king returned to it's original position but the rook still moved as to complete castling. Perhaps checking 'valid_move?' before castling completes would help here.
screen shot 2016-03-30 at 4 56 18 pm

**Comment by justinrjoseph** [comment]
I never claimed this implementation was finished. I never expected any of my recent PRs to be perfect from their initial merges. I simply wanted the fundamental implementations to be done for the remaining major tasks. I didn't even have check logic code to work against as I was building this out, and I wasn't interested in stubbing out my own code because it got to be an immense pain to maintain my files that way.

What you've pointed out is good and necessary though, and I'll need to work out those details.

**Comment by xJIsaac** [comment]
I'm confused, you had this tagged with a 'needs review' right? Well anyways it's ok Justin. 

The known issues shouldn't be merged but fortunately with what we have merged so far the issue should be resolved fairly easily with just a few additional checks. The recent merges allow us access to your 'in_check?' method. Perhaps we could merge the updates into this branch and rework it. I can work on it if you'd like me to.

**Comment by justinrjoseph** [comment]
Heh, of course it's OK. I suppose 'needs review' may have been misleading, but it's irrelevant at this point.

I would prefer to look at the issues myself first. I haven't had a legitimate opportunity to perform all the necessary checks. Thanks again for digging into those other rules.

**Comment by xJIsaac** [comment]
No problem. That sounds good.

**Comment by justinrjoseph** [comment]
As of 03/30/2016
- Resolved piece.rb and pieces controller merge conflicts
- Updated caste_move? method to check if king is moving within its home row (fixes king_test & castling_test)

**TO DO**:
- Account for additional scenarios pointed out by @j7isaac

**Comment by justinrjoseph** [comment]
As of 04/02/2016

game.rb
- Added captured?: false criteria to in_check? method for player_pieces so only pieces truly remaining are collected

king.rb
- Changed in castle_move?
  - Added comments specify rules checked
  - Added game.in_check? enemy_king_color to determine if game is in check from opponent's perspective
  - Added enemy_pieces_threatens_castle_path? method to determine if the two spaces the King must pass through to castle can be attacked by an enemy piece (especially prevents moving into check)
  - Added friendly_piece_blocks_castle_path? method to determine if a friendly piece occupies either of the two spaces the King must pass through to castle

piece.rb
- Cleaned up some indentation
- Added .where.not(color: color) criteria to enemy_piece query in piece_captured? method to fix bug where a piece could capture itself
- Added .where(captured?: false) critera to enemy_pieces query in move_would_cause_check? method so only enemy pieces truly remaining are collected

@j7isaac I believe these changes take care of the issues you pointed out a few days ago. Let me know if you notice anything else.

**Comment by xJIsaac** [comment]
:+1:  Appears you fixed everything I saw.

**Pull request merged**
