### PR TITLE
Valid move knight

### PR DESCRIPTION
**Pull request by justinrjoseph**

### CODE REVIEW

**Comment by justinrjoseph** [comment]
@conslo @msloekito So Martin and I were discussing the is_obstructed? method. According to Ken's gist for that task (https://gist.github.com/kenmazaika/92b81db9e977578c8d94), the A8 -> A6 example isn't making sense to us. How are we determining that a piece can't move to a square occupied by another of the same color if not by asking is_obstructed? Will we be coding a separate method for that, or something else?

**Comment by thisguycodes** [comment]
@justinrjoseph think about it like this: does having a piece at the location you're moving to obstruct the move?

No, because that's how capturing works. You can think of the rule like "you can't capture your own pieces", which fits into the rule set much less complicated than "you can move onto empty squares, or pieces of the other team if you do a capture" which sounds messy.

I imagine the logic you're asking about will be part of valid_move?, since capturing your own piece is not "valid"

**Comment by xJIsaac** [comment]
Is there a test for this model?

**Comment by xJIsaac** [comment]
Just asking because I need help on testing mine. Not sure how to create a game with a bishop where I want it.

**Comment by justinrjoseph** [comment]
Look at the replacement PR for this :) And by no means are my tests exhaustive. It's a starting point.

**Pull request closed without merging**
