### PR TITLE
add king_move? and valid_move? method to King model

### PR DESCRIPTION
**Pull request by msloekito**
will need is_obstructed? method and check? method.

I believe Seb started working on is_obstructed? method?

### CODE REVIEW

**Comment by justinrjoseph** [comment]
Checking whether a boolean method call returns true or false is redundant. Boolean methods already return true or false, so you don't need to supply _== true_ or _!= true_ comparisons. If you're checking for false, use the bang (!) operator before the method signature.

Also, what is _check_ for?

Essentially: 
before: king_move? == true && check? != true && is_obstructed? != true
after: king_move? && !check? && !is_obstructed?

**Comment by msloekito** [comment]
Check is also a Boolean value whether or not the particular position King is moving into is a "check" position, so king cannot move there. I'm not sure if this logic is included in the is_obstructed? Method?

**Comment by sanzencode** [comment]
I think there are going to have to be many more methods but if the method is encompassing all pieces and there respective moves then it makes sense that the king.rb inherits that from piece.rb so the checking of an obstructed move is not done at the individual piece level. Make sense??

**Comment by justinrjoseph** [comment]
This code still needs some clean-up. For consistency across the app it would be helpful to not have a separate king_move? method, but I will leave that decision to you. The _check_ call also shouldn't be included in this PR since that code hasn't been written yet. It will cause a NoMethod error if anyone interacts with the King in their local environments. Finally, we should have some tests for this valid_move?, and you can see examples in the PRs that have been merged recently.

**Pull request merged**
